<table height="600"><tr><td valign="top">
<b>PG Management</b>
<p style="text-align: justify">PG Management solution for PG have been designed to help PG Owners to manage entire PG with software like- Add/delete/edit PG, Rooms, Beds etc, we also provide information about Guest for payment due/add/relocate/remove guest, you can also manage account for each guest easily and this is also designed to reach out to the widest audience in the most cost-effective manner. We have customized solutions to Owner Individuals or Agents needs.<br/><br/>We have many different menu options for each individual mentioned bellow.&nbsp;<b>If you are using PG management service you will get Text Search Pack advertisement free of cost.</b></p>
<table>
<tr><td valign="top"><b>Manage PG Home</b><p style="text-align: justify">Under this menu we have task related to PG as an entity. You can view the PG information for as many PG you have, add more PG, delete the existing PG and edit the profile for the existing PG. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td><td>&nbsp;&nbsp;&nbsp;</td><td valign="top"><b>Manage Rooms</b><p style="text-align: justify">Under this menu we have task related to rooms in a PG as an entity. You can view the Room information for as many Rooms you have, add more Room, delete the existing Room and edit the profile for the existing Room. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td></tr>
<tr><td valign="top"><b>Manage Beds</b><p style="text-align: justify">Under this menu we have task related to Beds in a Room as an entity. You can view the Bed information for as many Beds you have, add more Bed, delete the existing Bed, edit the profile for the existing Bed and also you can see what all empty Beds you have. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td><td>&nbsp;&nbsp;&nbsp;</td><td valign="top"><b>Manage Guests</b><p style="text-align: justify">Under this menu we have task related to Guest on a Bed as an entity. You can view the Guest information for as many Guest you have, add more Guest, delete the existing Guest, edit the profile for the existing Guest and also you can see what all Guest you have in one PG. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td></tr>
<tr><td valign="top"><b>Bill Management</b><p style="text-align: justify">Under this menu we have task related to bill of guest living in the PG. We have task to view the due amount of a guest for the current and previous month, how many guest have already paid and also here we can edit room/bed rent. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td><td>&nbsp;&nbsp;&nbsp;</td><td valign="top"><b>PG Solution</b><p style="text-align: justify">Beside other solutions provided by PG Homes we also provide PG Goods management where you can manage the goods which are used in PG like-fan, bulb, bed etc and we also provide advertigemnet solution by which you can advertise you PG which in turn will reach out to much more audience. For more information&nbsp;<a href="customers.jsp?id=home" target="_blank">click here</a>.</p></td></tr>
</table>
</td><td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td></tr></table>
